format = "$all"
command_timeout = 1000

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'

[git_metrics]
disabled = false
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[time]
disabled = false
format = "🕙 [$time]($style) "

[battery]
disabled = false

[localip]
disabled = false
ssh_only = false
format = '@[$localipv4](red) '
